import { Router } from 'express';
import { z } from 'zod';
import bcrypt from 'bcryptjs';
import { pool,inTransaction } from '../../db/pool';
import { authenticate,allow } from '../../middleware/auth';
import { ApiError } from '../../shared/errors';
import { enqueueRecompute } from '../../jobs/queue';
import { pagination,paged } from '../../shared/pagination';

export const adminRouter=Router(); adminRouter.use(authenticate);
adminRouter.get('/resource-categories',async(req,res,next)=>{try{const {page,pageSize,offset}=pagination(req);const [rows,count]=await Promise.all([pool.query('SELECT * FROM resource_categories ORDER BY name LIMIT $1 OFFSET $2',[pageSize,offset]),pool.query('SELECT count(*) FROM resource_categories')]);res.json(paged(rows.rows,page,pageSize,count.rows[0].count));}catch(e){next(e);}});
adminRouter.post('/resource-categories',allow('ADMIN'),async(req,res,next)=>{try{const p=z.object({name:z.string().min(1).max(100),importance_weight:z.number().int().min(0).max(100)}).parse(req.body);const r=await inTransaction(async(c)=>{const created=await c.query('INSERT INTO resource_categories(name,importance_weight) VALUES($1,$2) RETURNING *',[p.name,p.importance_weight]);await c.query("INSERT INTO audit_logs(entity_type,entity_id,action,performed_by,new_value) VALUES('ResourceCategory',$1,'CREATE',$2,to_jsonb($3::json))",[created.rows[0].category_id,req.principal!.userId,JSON.stringify(p)]);return created.rows[0];});res.status(201).json(r);}catch(e){next(e);}});
adminRouter.patch('/resource-categories/:id',allow('ADMIN'),async(req,res,next)=>{try{
  const p=z.object({name:z.string().min(1).max(100).optional(),importance_weight:z.number().int().min(0).max(100).optional(),is_active:z.boolean().optional()}).refine(v=>Object.keys(v).length>0).parse(req.body);
  const row=await inTransaction(async(c)=>{const old=await c.query('SELECT * FROM resource_categories WHERE category_id=$1 FOR UPDATE',[req.params.id]);if(!old.rowCount)throw new ApiError(404,'NOT_FOUND','Resource category not found.');
    const next={...old.rows[0],...p}; await c.query('UPDATE resource_categories SET name=$2,importance_weight=$3,is_active=$4 WHERE category_id=$1',[req.params.id,next.name,next.importance_weight,next.is_active]);
    await c.query("INSERT INTO audit_logs(entity_type,entity_id,action,performed_by,old_value,new_value) VALUES('ResourceCategory',$1,'UPDATE',$2,$3::jsonb,$4::jsonb)",[req.params.id,req.principal!.userId,JSON.stringify({name:old.rows[0].name,importance_weight:old.rows[0].importance_weight,is_active:old.rows[0].is_active}),JSON.stringify({name:next.name,importance_weight:next.importance_weight,is_active:next.is_active})]);
    return next;
  });
  if(p.importance_weight!==undefined) await enqueueRecompute('category',req.params.id);
  res.json(row);
}catch(e){next(e);}});

adminRouter.get('/resources',async(req,res,next)=>{try{if(typeof req.query.category_id!=='string')throw new ApiError(400,'VALIDATION_ERROR','category_id is required.');const {page,pageSize,offset}=pagination(req);const [rows,count]=await Promise.all([pool.query('SELECT * FROM resources WHERE category_id=$1 ORDER BY name LIMIT $2 OFFSET $3',[req.query.category_id,pageSize,offset]),pool.query('SELECT count(*) FROM resources WHERE category_id=$1',[req.query.category_id])]);res.json(paged(rows.rows,page,pageSize,count.rows[0].count));}catch(e){next(e);}});
adminRouter.post('/resources',allow('ADMIN'),async(req,res,next)=>{try{const p=z.object({category_id:z.string().uuid(),name:z.string().min(1).max(150),unit_of_measure:z.string().min(1).max(30)}).parse(req.body);const r=await inTransaction(async(c)=>{const created=await c.query('INSERT INTO resources(category_id,name,unit_of_measure) VALUES($1,$2,$3) RETURNING *',[p.category_id,p.name,p.unit_of_measure]);await c.query("INSERT INTO audit_logs(entity_type,entity_id,action,performed_by,new_value) VALUES('Resource',$1,'CREATE',$2,to_jsonb($3::json))",[created.rows[0].resource_id,req.principal!.userId,JSON.stringify(p)]);return created.rows[0];});res.status(201).json(r);}catch(e){next(e);}});

adminRouter.get('/weight-configs',allow('ADMIN'),async(req,res,next)=>{try{const {page,pageSize,offset}=pagination(req);const [rows,count]=await Promise.all([pool.query('SELECT * FROM weight_configs ORDER BY created_at DESC LIMIT $1 OFFSET $2',[pageSize,offset]),pool.query('SELECT count(*) FROM weight_configs')]);res.json(paged(rows.rows,page,pageSize,count.rows[0].count));}catch(e){next(e);}});
const configBody=z.object({severity_weight:z.number().min(0).max(1),importance_weight:z.number().min(0).max(1),students_weight:z.number().min(0).max(1),alternative_weight:z.number().min(0).max(1),condition_weight:z.number().min(0).max(1),critical_threshold:z.number().int().min(0).max(100),high_threshold:z.number().int().min(0).max(100),medium_threshold:z.number().int().min(0).max(100)});
adminRouter.post('/weight-configs',allow('ADMIN'),async(req,res,next)=>{try{const p=configBody.parse(req.body);const sum=p.severity_weight+p.importance_weight+p.students_weight+p.alternative_weight+p.condition_weight;if(Math.abs(sum-1)>.001||!(p.critical_threshold>p.high_threshold&&p.high_threshold>p.medium_threshold))throw new ApiError(400,'INVALID_WEIGHT_CONFIG','Weights must sum to 1.000 (+/- 0.001) and thresholds must descend.');const result=await inTransaction(async(c)=>{const r=await c.query(`INSERT INTO weight_configs(severity_weight,importance_weight,students_weight,alternative_weight,condition_weight,critical_threshold,high_threshold,medium_threshold,created_by)
  VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[p.severity_weight,p.importance_weight,p.students_weight,p.alternative_weight,p.condition_weight,p.critical_threshold,p.high_threshold,p.medium_threshold,req.principal!.userId]);await c.query("INSERT INTO audit_logs(entity_type,entity_id,action,performed_by,new_value) VALUES('WeightConfig',$1,'CREATE',$2,to_jsonb($3::json))",[r.rows[0].config_id,req.principal!.userId,JSON.stringify(p)]);return r.rows[0];});res.status(201).json(result);}catch(e){next(e);}});
adminRouter.patch('/weight-configs/:id/activate',allow('ADMIN'),async(req,res,next)=>{try{const p=z.object({expected_version:z.number().int().positive()}).parse(req.body);const r=await inTransaction(async(c)=>{const target=await c.query('SELECT * FROM weight_configs WHERE config_id=$1 FOR UPDATE',[req.params.id]);if(!target.rowCount)throw new ApiError(404,'NOT_FOUND','Weight configuration not found.');if(Number(target.rows[0].version)!==p.expected_version)throw new ApiError(409,'VERSION_CONFLICT','Weight configuration changed since it was read.',{current:target.rows[0]});const current=await c.query('SELECT config_id FROM weight_configs WHERE is_active=true FOR UPDATE');await c.query('UPDATE weight_configs SET is_active=false,version=version+1 WHERE is_active=true');await c.query('UPDATE weight_configs SET is_active=true,version=version+1 WHERE config_id=$1',[req.params.id]);await c.query("INSERT INTO audit_logs(entity_type,entity_id,action,performed_by,old_value,new_value) VALUES('WeightConfig',$1,'ACTIVATE',$2,jsonb_build_object('active_config',$3),jsonb_build_object('active_config',$1))",[req.params.id,req.principal!.userId,current.rows[0]?.config_id??null]);return (await c.query('SELECT * FROM weight_configs WHERE config_id=$1',[req.params.id])).rows[0];});await enqueueRecompute('all');res.json(r);}catch(e){next(e);}});

adminRouter.patch('/organizations/:id/verify',allow('ADMIN'),async(req,res,next)=>{try{const p=z.object({status:z.enum(['VERIFIED','REJECTED'])}).parse(req.body);const r=await inTransaction(async(c)=>{const old=await c.query('SELECT verification_status FROM organizations WHERE org_id=$1 FOR UPDATE',[req.params.id]);if(!old.rowCount)throw new ApiError(404,'NOT_FOUND','Organization not found.');await c.query('UPDATE organizations SET verification_status=$2 WHERE org_id=$1',[req.params.id,p.status]);await c.query("INSERT INTO audit_logs(entity_type,entity_id,action,performed_by,old_value,new_value) VALUES('Organization',$1,'VERIFY',$2,jsonb_build_object('verification_status',$3),jsonb_build_object('verification_status',$4))",[req.params.id,req.principal!.userId,old.rows[0].verification_status,p.status]);return (await c.query('SELECT * FROM organizations WHERE org_id=$1',[req.params.id])).rows[0];});res.json(r);}catch(e){next(e);}});

adminRouter.get('/audit-logs',allow('ADMIN'),async(req,res,next)=>{try{const {page,pageSize,offset}=pagination(req);const [rows,count]=await Promise.all([pool.query('SELECT * FROM audit_logs ORDER BY performed_at DESC LIMIT $1 OFFSET $2',[pageSize,offset]),pool.query('SELECT count(*) FROM audit_logs')]);res.json(paged(rows.rows,page,pageSize,count.rows[0].count));}catch(e){next(e);}});
adminRouter.get('/users',allow('ADMIN'),async(req,res,next)=>{try{const {page,pageSize,offset}=pagination(req);const [rows,count]=await Promise.all([pool.query('SELECT user_id,email,role,full_name,phone,is_active,last_login_at,created_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2',[pageSize,offset]),pool.query('SELECT count(*) FROM users')]);res.json(paged(rows.rows,page,pageSize,count.rows[0].count));}catch(e){next(e);}});
adminRouter.get('/organizations',allow('ADMIN'),async(req,res,next)=>{try{const {page,pageSize,offset}=pagination(req);const [rows,count]=await Promise.all([pool.query('SELECT * FROM organizations ORDER BY created_at DESC LIMIT $1 OFFSET $2',[pageSize,offset]),pool.query('SELECT count(*) FROM organizations')]);res.json(paged(rows.rows,page,pageSize,count.rows[0].count));}catch(e){next(e);}});

adminRouter.post('/users',allow('ADMIN'),async(req,res,next)=>{try{
  const p=z.object({email:z.string().email().max(255),password:z.string().min(10).regex(/[A-Za-z]/).regex(/[0-9]/),full_name:z.string().min(1).max(150),phone:z.string().regex(/^\+[1-9]\d{1,14}$/).optional(),role:z.enum(['FIELD_COORDINATOR','ADMIN'])}).parse(req.body);
  const r=await inTransaction(async(c)=>{const user=await c.query('INSERT INTO users(email,password_hash,role,full_name,phone) VALUES(lower($1),$2,$3,$4,$5) RETURNING user_id,email,role,full_name,phone,is_active',[p.email,await bcrypt.hash(p.password,12),p.role,p.full_name,p.phone??null]);await c.query("INSERT INTO audit_logs(entity_type,entity_id,action,performed_by,new_value) VALUES('User',$1,'CREATE',$2,jsonb_build_object('role',$3,'email',$4))",[user.rows[0].user_id,req.principal!.userId,p.role,p.email]);return user.rows[0];});res.status(201).json(r);
}catch(e){next(e);}});
adminRouter.patch('/users/:id',allow('ADMIN'),async(req,res,next)=>{try{
  const p=z.object({role:z.enum(['SCHOOL','NGO','ADMIN','FIELD_COORDINATOR']).optional(),is_active:z.boolean().optional()}).refine(v=>Object.keys(v).length>0).parse(req.body);
  const r=await inTransaction(async(c)=>{const old=await c.query('SELECT user_id,role,is_active FROM users WHERE user_id=$1 FOR UPDATE',[req.params.id]);if(!old.rowCount)throw new ApiError(404,'NOT_FOUND','User not found.');const nextRole=p.role??old.rows[0].role,nextActive=p.is_active??old.rows[0].is_active;await c.query('UPDATE users SET role=$2,is_active=$3 WHERE user_id=$1',[req.params.id,nextRole,nextActive]);if(p.role)await c.query("INSERT INTO audit_logs(entity_type,entity_id,action,performed_by,old_value,new_value) VALUES('User',$1,'ROLE_CHANGE',$2,jsonb_build_object('role',$3),jsonb_build_object('role',$4))",[req.params.id,req.principal!.userId,old.rows[0].role,nextRole]);if(p.is_active!==undefined)await c.query("INSERT INTO audit_logs(entity_type,entity_id,action,performed_by,old_value,new_value) VALUES('User',$1,'ACTIVE_CHANGE',$2,jsonb_build_object('is_active',$3),jsonb_build_object('is_active',$4))",[req.params.id,req.principal!.userId,old.rows[0].is_active,nextActive]);return (await c.query('SELECT user_id,email,role,full_name,phone,is_active,last_login_at FROM users WHERE user_id=$1',[req.params.id])).rows[0];});res.json(r);
}catch(e){next(e);}});
adminRouter.post('/field-coordinators/:id/schools/:schoolId',allow('ADMIN'),async(req,res,next)=>{try{
  await inTransaction(async(c)=>{const user=await c.query("SELECT 1 FROM users WHERE user_id=$1 AND role='FIELD_COORDINATOR'",[req.params.id]);if(!user.rowCount)throw new ApiError(404,'NOT_FOUND','Field Coordinator not found.');const school=await c.query('SELECT 1 FROM schools WHERE school_id=$1',[req.params.schoolId]);if(!school.rowCount)throw new ApiError(404,'NOT_FOUND','School not found.');await c.query('INSERT INTO field_coordinator_schools(coordinator_user_id,school_id) VALUES($1,$2)',[req.params.id,req.params.schoolId]);await c.query("INSERT INTO audit_logs(entity_type,entity_id,action,performed_by,new_value) VALUES('FieldCoordinatorAssignment',$1,'CREATE',$2,jsonb_build_object('school_id',$3))",[req.params.id,req.principal!.userId,req.params.schoolId]);});res.status(201).json({coordinator_user_id:req.params.id,school_id:req.params.schoolId});
}catch(e){next(e);}});
