import express from 'express';
import { authRouter } from './modules/auth/routes';
import { schoolRouter } from './modules/schools/routes';
import { requirementRouter } from './modules/requirements/routes';
import { adminRouter } from './modules/admin/routes';
import { reportRouter } from './modules/reports/routes';
import { authenticate } from './middleware/auth';
import { errorHandler } from './shared/errors';
import { pool } from './db/pool';

export const app=express();
app.disable('x-powered-by');
app.use(express.json({limit:'1mb'}));
app.get('/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({status:'ok'});}catch{res.status(503).json({status:'unavailable'});}});
app.use('/api/v1/auth',authRouter);
app.use('/api/v1',schoolRouter);
app.use('/api/v1',requirementRouter);
app.use('/api/v1',adminRouter);
app.use('/api/v1',reportRouter);
app.get('/api/v1/session',authenticate,(req,res)=>res.json({user_id:req.principal!.userId,role:req.principal!.role}));
app.use((_req,res)=>res.status(404).json({error:{code:'NOT_FOUND',message:'Endpoint not found.'}}));
app.use(errorHandler);
