import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api, apiMode } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { DataTable, FormField, Notice, PageTitle, Pagination, StateBadge } from '../components/Shared';
import { useAsync } from '../hooks/useAsync';
import { mockSchools } from '../api/mock';
import type { Requirement, RequirementStatus, ResourceCategory } from '../types';

export function RequirementsPage() {
  const { user } = useAuth();
  const [page, setPage] = useState(1); const [priority, setPriority] = useState(''); const [status, setStatus] = useState(''); const [district, setDistrict] = useState(''); const [category, setCategory] = useState('');
  const categories = useAsync(() => api.resources.categories());
  const result = useAsync(() => api.requirements.list({ page, page_size: 10, priority_class: priority, status, district: district || undefined, resource_category: category || undefined }), [page, priority, status, district, category]);
  let rows = result.data?.data ?? [];
  if (apiMode === 'mock' && user?.role === 'SCHOOL') rows = rows.filter((r) => r.school_id === 'sch-001');
  if (apiMode === 'mock' && user?.role === 'FIELD_COORDINATOR') rows = rows.filter((r) => ['Kolar', 'Tumakuru'].includes(r.district));
  const districts = apiMode === 'mock' ? [...new Set(mockSchools.map((s) => s.district))] : [];
  return <>
    <PageTitle title="Requirements" description="Review resource gaps from verified school assessments and track follow-up status." />
    <Notice>Requirements are generated by the backend when an assessment is verified. Manual creation and general editing are not supported; use the status actions on a requirement record.</Notice>
    <section className="panel filter-panel"><div className="filter-grid filter-grid-4">
      <FormField label="Priority" htmlFor="req-priority"><select id="req-priority" value={priority} onChange={(e) => { setPriority(e.target.value); setPage(1); }}><option value="">All priorities</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></FormField>
      <FormField label="Status" htmlFor="req-status"><select id="req-status" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option>{['OPEN','UNDER_REVIEW','ACCEPTED','IN_PROGRESS','PARTIALLY_COMPLETED','COMPLETED','NOT_FEASIBLE','DISPUTED','CLOSED'].map((value) => <option key={value}>{value}</option>)}</select></FormField>
      {apiMode === 'mock' ? <FormField label="District" htmlFor="req-district"><select id="req-district" value={district} onChange={(e) => { setDistrict(e.target.value); setPage(1); }}><option value="">All districts</option>{districts.map((d) => <option key={d}>{d}</option>)}</select></FormField> : <FormField label="District" htmlFor="req-district"><input id="req-district" value={district} onChange={(e) => { setDistrict(e.target.value); setPage(1); }} /></FormField>}
      <FormField label="Resource category" htmlFor="req-category"><select id="req-category" value={category} onChange={(e) => { setCategory(e.target.value); setPage(1); }}><option value="">All categories</option>{(categories.data?.data ?? []).map((c: ResourceCategory) => <option key={c.category_id} value={c.category_id}>{c.name}</option>)}</select></FormField>
    </div></section>
    {result.error ? <Notice tone="error">{result.error}</Notice> : <section className="panel"><DataTable<Requirement> rows={rows} rowKey={(row) => row.requirement_id} columns={[
      { key: 'school_name', label: 'School', render: (row) => <Link to={`/requirements/${row.requirement_id}`}>{row.school_name}</Link> },
      { key: 'resource_name', label: 'Resource' }, { key: 'district', label: 'District' }, { key: 'gap_qty', label: 'Gap quantity' },
      { key: 'final_score', label: 'Priority score', render: (row) => Number(row.final_score).toFixed(2) }, { key: 'priority_class', label: 'Priority', render: (row) => <StateBadge value={row.priority_class} /> },
      { key: 'status', label: 'Status', render: (row) => <StateBadge value={row.status} /> },
      { key: 'data_changed_since_acceptance', label: 'Assessment update', render: (row) => row.data_changed_since_acceptance ? <span className="text-alert">New verified data</span> : '—' },
    ]} /><Pagination page={page} pageSize={10} total={result.data?.total_count ?? 0} onChange={setPage} /></section>}
  </>;
}

const nextByStatus: Record<string, RequirementStatus[]> = {
  ACCEPTED: ['IN_PROGRESS'], IN_PROGRESS: ['PARTIALLY_COMPLETED', 'COMPLETED', 'NOT_FEASIBLE'],
  PARTIALLY_COMPLETED: ['IN_PROGRESS', 'COMPLETED', 'NOT_FEASIBLE'], NOT_FEASIBLE: ['OPEN'], DISPUTED: ['IN_PROGRESS', 'CLOSED'],
};

export function RequirementDetailPage() {
  const { id = '' } = useParams();
  const { user } = useAuth();
  const result = useAsync(() => api.requirements.detail(id), [id]);
  const [newStatus, setNewStatus] = useState(''); const [fulfilledQty, setFulfilledQty] = useState(''); const [reason, setReason] = useState(''); const [comments, setComments] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const row = result.data as (Requirement & { fulfilled_qty?: number; accepted_gap_qty?: number; interventions?: unknown[]; feedback?: unknown[] }) | null;
  async function accept() { if (!row) return; setError(''); setMessage(''); try { await api.requirements.accept(row.requirement_id, row.version); setMessage('The requirement was accepted for action.'); result.reload(); } catch (e) { setError(e instanceof Error ? e.message : 'The action could not be completed.'); } }
  async function saveStatus() { if (!row || !newStatus) return; setError(''); setMessage('');
    try {
      await api.requirements.updateStatus(row.requirement_id, { new_status: newStatus, expected_version: row.version, ...(fulfilledQty ? { fulfilled_qty: Number(fulfilledQty) } : {}), ...(reason ? { reason } : {}), ...(comments ? { comments, action_description: comments } : {}) });
      setMessage('The requirement status was updated.'); setNewStatus(''); result.reload();
    } catch (e) { setError(e instanceof Error ? e.message : 'The status could not be updated.'); }
  }
  async function acknowledge() { if (!row) return; try { await api.requirements.acknowledgeChange(row.requirement_id, row.version); setMessage('The latest verified assessment data was acknowledged.'); result.reload(); } catch (e) { setError(e instanceof Error ? e.message : 'The change could not be acknowledged.'); } }
  async function confirm(confirmation: 'CONFIRMED' | 'DISPUTED') { if (!row) return; try { await api.requirements.feedback(row.requirement_id, { confirmation, expected_version: row.version, comments }); setMessage(confirmation === 'CONFIRMED' ? 'School confirmation was recorded.' : 'The requirement was referred for dispute review.'); result.reload(); } catch (e) { setError(e instanceof Error ? e.message : 'Feedback could not be recorded.'); } }
  if (result.loading) return <p className="muted">Loading requirement details…</p>;
  if (result.error || !row) return <Notice tone="error">{result.error || 'Requirement record was not found.'}</Notice>;
  const options = [...(nextByStatus[row.status] ?? [])];
  if (user?.role === 'ADMIN' && row.status === 'UNDER_REVIEW') options.push('OPEN');
  const canAccept = user?.role === 'NGO' && ['OPEN', 'UNDER_REVIEW'].includes(row.status);
  return <>
    <PageTitle title="Requirement details" description={`${row.school_name} · ${row.district}`} actions={<Link className="button button-secondary" to="/requirements">Back to requirements</Link>} />
    {error && <Notice tone="error">{error}</Notice>}{message && <Notice tone="success">{message}</Notice>}
    {row.data_changed_since_acceptance && <Notice tone="warning">A newer verified assessment is available for this school and resource. Review the update before acknowledging it.</Notice>}
    <section className="detail-grid panel"><div><span className="detail-label">Resource</span><strong>{row.resource_name}</strong></div><div><span className="detail-label">Category</span><strong>{row.category_name}</strong></div><div><span className="detail-label">Gap quantity</span><strong>{row.gap_qty}</strong></div><div><span className="detail-label">Gap ratio</span><strong>{(Number(row.gap_ratio) * 100).toFixed(1)}%</strong></div><div><span className="detail-label">Priority score</span><strong>{Number(row.final_score).toFixed(2)}</strong></div><div><span className="detail-label">Priority and status</span><span><StateBadge value={row.priority_class} /> <StateBadge value={row.status} /></span></div></section>
    <div className="action-columns">
      {canAccept && <section className="panel action-panel"><h2>Accept requirement</h2><p>Acceptance assigns this requirement to your organisation for action.</p><button className="button button-primary" onClick={accept}>Accept requirement</button></section>}
      {row.data_changed_since_acceptance && user?.role === 'NGO' && <section className="panel action-panel"><h2>Acknowledge assessment update</h2><p>Update the requirement to the latest verified resource data.</p><button className="button button-secondary" onClick={acknowledge}>Acknowledge verified data</button></section>}
      {options.length > 0 && (user?.role === 'NGO' || user?.role === 'ADMIN') && <section className="panel action-panel form-stack"><h2>Update status</h2><FormField label="New status" htmlFor="next-status"><select id="next-status" value={newStatus} onChange={(e) => setNewStatus(e.target.value)}><option value="">Select a permitted transition</option>{options.map((value) => <option key={value}>{value}</option>)}</select></FormField>
        {newStatus === 'PARTIALLY_COMPLETED' && <FormField label="Quantity fulfilled" htmlFor="fulfilled"><input id="fulfilled" type="number" min="1" max={row.accepted_gap_qty ?? row.gap_qty} value={fulfilledQty} onChange={(e) => setFulfilledQty(e.target.value)} /></FormField>}
        {['NOT_FEASIBLE', 'OPEN'].includes(newStatus) && <FormField label="Reason (minimum 10 characters)" htmlFor="transition-reason"><textarea id="transition-reason" minLength={10} required value={reason} onChange={(e) => setReason(e.target.value)} /></FormField>}
        {user?.role === 'ADMIN' && row.status === 'DISPUTED' && newStatus === 'CLOSED' && <FormField label="Administrative resolution comment" htmlFor="resolution-comment"><textarea id="resolution-comment" required value={comments} onChange={(e) => setComments(e.target.value)} /></FormField>}
        <FormField label="Comments" htmlFor="transition-comments"><textarea id="transition-comments" rows={3} value={comments} onChange={(e) => setComments(e.target.value)} /></FormField><button className="button button-primary" disabled={!newStatus} onClick={saveStatus}>Save status</button>
      </section>}
      {row.status === 'COMPLETED' && user?.role === 'SCHOOL' && <section className="panel action-panel"><h2>School confirmation</h2><p>Confirm completion or refer the result for administrative review.</p><label className="field"><span>Comments</span><textarea rows={3} value={comments} onChange={(e) => setComments(e.target.value)} /></label><div className="form-actions"><button className="button button-primary" onClick={() => confirm('CONFIRMED')}>Confirm completion</button><button className="button button-secondary" onClick={() => confirm('DISPUTED')}>Report a disagreement</button></div></section>}
    </div>
    <section className="panel"><h2>Intervention and feedback history</h2><p className="muted">{row.interventions?.length ?? 0} intervention entries · {row.feedback?.length ?? 0} feedback entries</p><p>Detailed history is available in the school report timeline.</p></section>
  </>;
}
